const INSTRUMENTS = {
  xun: {
    id: 'xun', name: 'Xun', native: '埙',
    region: 'China', regionType: 'east', regionLabel: 'East Asia · China',
    period: 'ancient', periodLabel: 'Ancient · Before 500 CE',
    type: 'wind', typeLabel: '🌬️ Blow into mic',
    shortDesc: 'Ancient clay vessel flute',
    history: 'The xun is one of the oldest musical instruments in Chinese history, with origins dating back approximately 7,000 years. Made from fired clay, this egg-shaped vessel flute was discovered at prehistoric sites across the Yellow River basin. It was used in ancient ritual ceremonies and later became part of the imperial court orchestra during the Zhou Dynasty (1046–256 BCE). Its haunting, muted tone was believed to carry prayers between the human and spiritual worlds.',
    howToPlay: 'Step 1 — start the sound: blow into your microphone until the breath meter lights up, OR press and hold the "Hold to Blow" button with one finger. Step 2 — change pitch: while the sound is playing, tap the numbered hole buttons to open and close them. Each hole shifts the note, and pressing multiple holes at once creates a different pitch. Try holding ① + ③ versus ② + ④ — they sound different even though you\'re pressing two holes each time!',
    notes: [261.63, 293.66, 329.63, 392.00, 440.00, 493.88],
    noteNames: ['C', 'D', 'E', 'G', 'A', 'B'],
    holes: ['①', '②', '③', '④', '⑤'],
    combos: { '00000':0, '10000':0, '11000':1, '01000':1, '11100':2, '11010':2, '11110':3, '11111':4 },
    photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Xunfront.jpg',
  },
  suling: {
    id: 'suling', name: 'Suling', native: 'ᬲᬸᬮᬶᬂ',
    region: 'Indonesia (Bali)', regionType: 'southeast', regionLabel: 'Southeast Asia · Bali',
    period: 'ancient', periodLabel: 'Ancient · Before 500 CE',
    type: 'wind', typeLabel: '🌬️ Blow into mic',
    shortDesc: 'Balinese bamboo end-blown flute',
    history: 'The suling is an ancient Balinese and Javanese bamboo flute with roots thousands of years old. It is integral to the gamelan ensemble and used in Hindu-Balinese ceremonies, shadow puppet theater (wayang), and meditation rituals. The Balinese suling is held at a diagonal and blown across a small opening at the end. Its delicate, airy tone is said to mimic the voice of the forest and the wind through the rice fields of Bali.',
    howToPlay: 'Step 1 — start the sound: blow into your microphone, OR press and hold the "Hold to Blow" button with one finger. Step 2 — change pitch: while still blowing or holding, press the numbered hole buttons with your other fingers. Different holes produce different notes — try holding ① + ② versus ③ + ④ to hear them change. Blow harder for a fuller sound, softer for a more delicate tone.',
    notes: [293.66, 329.63, 369.99, 440.00, 493.88],
    noteNames: ['D', 'E', 'F♯', 'A', 'B'],
    holes: ['①', '②', '③', '④'],
    combos: { '0000':0, '1000':0, '1100':1, '1110':2, '0110':2, '1111':3, '0111':4 },
    photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Kacapi-suling.JPG',
  },
  veena: {
    id: 'veena', name: 'Veena', native: 'வீணை',
    region: 'India', regionType: 'south', regionLabel: 'South Asia · India',
    period: 'ancient', periodLabel: 'Ancient · Before 500 CE',
    type: 'string', typeLabel: '🎸 Glide your finger',
    shortDesc: 'Sacred Indian plucked lute',
    history: 'The veena is one of the oldest string instruments in the world, with references in the Rigveda dating to around 1500 BCE. The goddess Saraswati — deity of music, knowledge, and the arts — is always depicted holding a veena, making it the most revered instrument in Indian classical music. The Saraswati veena features four main melody strings, three drone strings, and twenty-four bronze frets over a long neck with two resonating gourds carved from jackwood. Its rich, resonant tone has been central to Carnatic music for millennia.',
    howToPlay: 'Swipe or drag your finger across the strings on screen. Each string is tuned to a different note — move from left (low) to right (high) to glide through the scale. Try plucking individual strings by tapping, or slide slowly across all strings for a cascading arpeggio effect.',
    notes: [196.00, 220.00, 261.63, 293.66, 329.63],
    noteNames: ['Sa', 'Ri', 'Ga', 'Pa', 'Dha'],
    stringColor: '#C8895A',
    photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Veena_Vina_string_musical_instrument_India.jpg',
  },
  gayageum: {
    id: 'gayageum', name: 'Gayageum', native: '가야금',
    region: 'Korea', regionType: 'east', regionLabel: 'East Asia · Korea',
    period: 'classical', periodLabel: 'Classical · 500–1500 CE',
    type: 'string', typeLabel: '🎸 Glide your finger',
    shortDesc: 'Korea\'s iconic 12-string zither',
    history: 'The gayageum is Korea\'s most beloved traditional instrument, created during the Gaya confederacy in the 6th century CE. According to the Samguk Sagi chronicle, King Gasil commissioned musician Ureuk to create the instrument, who composed twelve original pieces — one for each string. The gayageum features twelve silk strings stretched over movable bridges (anjok) on a hollow resonance body made from paulownia wood. It has been played continuously for over 1,500 years in Korean court music (jeongganbo) and folk music (sanjo).',
    howToPlay: 'Swipe or drag across the strings to play. In traditional performance, the right hand plucks while the left hand presses strings behind the bridges to create vibrato and pitch bends. Try gliding slowly across all strings for a meditative sound, or tap individual strings in rhythm.',
    notes: [261.63, 311.13, 349.23, 392.00, 466.16, 523.25, 622.25, 698.46],
    noteNames: ['황', '태', '중', '임', '남', '청황', '청태', '청중'],
    stringColor: '#E8E0C0',
    photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Korean_Ka_Ya_Kum_(Gayageum),_Traditional_12-string_Instrument.jpg',
  },
  gamelan: {
    id: 'gamelan', name: 'Gamelan', native: 'ᬕᬫᭂᬮᬦ᭄',
    region: 'Indonesia', regionType: 'southeast', regionLabel: 'Southeast Asia · Indonesia',
    period: 'classical', periodLabel: 'Classical · 500–1500 CE',
    type: 'percussion', layout: 'gamelan', typeLabel: '🥁 Tap the bars',
    shortDesc: 'Indonesian bronze metallophone ensemble',
    history: 'The gamelan is an ensemble of percussion instruments from Java and Bali with roots in the Hindu-Buddhist kingdoms of the 8th to 10th centuries CE. The word comes from the Javanese "gamel," meaning to strike. The ensemble includes bronze metallophones (saron, gender), gongs (gong ageng, kenong), drums (kendang), and a bamboo flute (suling). Each instrument plays interlocking rhythmic patterns called "kotekan," creating a shimmering, interwoven texture. In 2021, UNESCO inscribed Indonesian gamelan as an Intangible Cultural Heritage of Humanity.',
    howToPlay: 'Tap each bronze bar to play its note. The bars are arranged from lowest pitch (widest, bottom) to highest (narrowest, top). In a real gamelan ensemble, each musician plays specific repeating patterns that interlock with the others. Try creating your own repeating patterns!',
    notes: [261.63, 329.63, 392.00, 523.25, 659.25],
    noteNames: ['Nem', 'Ro', 'Lu', 'Lima', 'Barang'],
    bars: ['Nem', 'Ro', 'Lu', 'Lima', 'Barang'],
    photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Gamelan_degung,_Musical_Instruments_Museum,_Phoenix,_Arizona.jpg',
  },
  tabla: {
    id: 'tabla', name: 'Tabla', native: 'तबला',
    region: 'India', regionType: 'south', regionLabel: 'South Asia · India',
    period: 'classical', periodLabel: 'Classical · 500–1500 CE',
    type: 'percussion', layout: 'tabla', typeLabel: '🥁 Tap the drums',
    shortDesc: 'Indian paired hand drums',
    history: 'The tabla is a pair of hand drums that forms the rhythmic backbone of Hindustani classical music from North India. The smaller right drum (dayan) is made of wood and tuned to a specific pitch. The larger left drum (bayan) is made of metal and produces a deep bass resonance. Both drum heads feature a distinctive black paste (siyahi) made from iron filings and starch, which gives the tabla its unique tonal complexity and allows the drum to be tuned to precise pitches. The tabla is central to Indian classical, devotional, and film music.',
    howToPlay: 'Tap the Dayan (right drum) for higher tones and the Bayan (left drum) for bass. Traditional tabla playing uses a system of spoken syllables called bols — "na," "tin," "dha," "ge" — each representing a different stroke. Try alternating between the two drums to feel a basic rhythm.',
    notes: [392.00, 146.83],
    noteNames: ['Dayan', 'Bayan'],
    pads: [
      { label: 'Dayan', sub: 'Na · Tin · Ta', note: 0 },
      { label: 'Bayan', sub: 'Ge · Dha · Ka', note: 1 },
    ],
    photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Prop._Tabla.jpg',
  },
  janggu: {
    id: 'janggu', name: 'Janggu', native: '장구',
    region: 'Korea', regionType: 'east', regionLabel: 'East Asia · Korea',
    period: 'modern', periodLabel: 'Modern Traditional · 1500 CE–Present',
    type: 'percussion', layout: 'janggu', typeLabel: '🥁 Tap the drum heads',
    shortDesc: 'Korean hourglass drum',
    history: 'The janggu is Korea\'s most representative percussion instrument, recognized by its distinctive hourglass shape connecting two drum heads of different sizes. It appears in historical records and paintings from the Goryeo Dynasty (918–1392). The right head (채편, chae-pyeon) is struck with a thin bamboo stick for a bright, sharp tone, while the left head (궁편, gung-pyeon) is struck with a padded mallet for a deep, resonant boom. The janggu is central to pansori storytelling, farmer\'s music (nongak), and royal court music. Its rhythmic patterns, called jangdan, range from slow and meditative to intensely fast.',
    howToPlay: 'Tap the left head (궁편) for the deep "KUNG" sound and the right head (채편) for the bright "DEOK" sound. Try the basic Jungmori pattern: KUNG — deok — KUNG — deok. The combination of these two contrasting tones gives the janggu its hypnotic character.',
    notes: [523.25, 130.81],
    pads: [
      { label: '채편', sub: 'Deok · bright', note: 0 },
      { label: '궁편', sub: 'Kung · deep', note: 1 },
    ],
    photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Korean.Music-Janggu-01.jpg',
  },
  dantranh: {
    id: 'dantranh', name: 'Đàn Tranh', native: 'đàn tranh',
    region: 'Vietnam', regionType: 'southeast', regionLabel: 'Southeast Asia · Vietnam',
    period: 'modern', periodLabel: 'Modern Traditional · 1500 CE–Present',
    type: 'string', typeLabel: '🎸 Glide your finger',
    shortDesc: 'Vietnamese 16-string zither',
    history: 'The đàn tranh is a Vietnamese zither with sixteen to twenty-five metal strings stretched over a long resonating box. Related to the Chinese guzheng and Korean gayageum, each instrument developed its own distinct tuning, ornamentation, and musical personality over centuries. The đàn tranh is central to Vietnamese chamber music (nhạc thính phòng), folk songs (dân ca), and the popular cải lương theater form. Its characteristic ornament — pressing the string behind the bridge to create a sliding, "crying" pitch — gives Vietnamese music much of its emotional expressiveness.',
    howToPlay: 'Swipe or drag across the strings to play. The đàn tranh is known for its vibrato and pitch slides — after plucking a string, try pressing and releasing it slightly to create the signature "rung" (vibrato) effect. Glide slowly across the strings from left to right for a cascading melody.',
    notes: [293.66, 349.23, 392.00, 466.16, 523.25, 587.33],
    noteNames: ['Hò', 'Xự', 'Sang', 'Xê', 'Cống', 'Liu'],
    stringColor: '#A8C0C8',
    photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Flickr_-_dalbera_-_Huong_Thanh_Trio,_(mus%C3%A9e_Guimet,_Paris).jpg',
  },
  shakuhachi: {
    id: 'shakuhachi', name: 'Shakuhachi', native: '尺八',
    region: 'Japan', regionType: 'east', regionLabel: 'East Asia · Japan',
    period: 'modern', periodLabel: 'Modern Traditional · 1500 CE–Present',
    type: 'wind', typeLabel: '🌬️ Blow into mic',
    shortDesc: 'Japanese Zen bamboo flute',
    history: 'The shakuhachi is an end-blown bamboo flute that arrived in Japan from Tang Dynasty China in the 7th century and was subsequently refined into a uniquely Japanese instrument. Its name comes from its traditional length: one shaku (尺) and eight (八) sun — approximately 54.5 cm. In the 17th century, monks of the Fuke Zen sect used the shakuhachi as a meditative tool, playing solo pieces called honkyoku as a form of "blowing Zen" (suizen). The instrument became renowned for its expressive, breathy tone and its ability to evoke natural sounds — wind through bamboo, flowing water, distant birdsong.',
    howToPlay: 'Step 1 — start the sound: blow a long, steady breath into your microphone, OR press and hold the "Hold to Blow" button with one finger. Step 2 — change pitch: while the sound is active, press and release the numbered hole buttons with your other fingers. The key is to keep blowing (or holding the button) the whole time — the holes only change the pitch, they don\'t start the sound. Try sliding slowly from ① → ② → ③ while holding a steady breath for a meditative melody.',
    notes: [293.66, 329.63, 392.00, 440.00, 493.88, 587.33],
    noteNames: ['D', 'E', 'G', 'A', 'B', 'D\''],
    holes: ['①', '②', '③', '④', '⑤'],
    combos: { '00000':0, '10000':0, '11000':1, '11100':2, '11110':3, '11111':4 },
    photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Shakuhachi-2.png',
  },
};

const PERIODS = [
  { id:'ancient',  label:'Ancient',            dates:'Before 500 CE',          instruments:['xun','suling','veena'] },
  { id:'classical',label:'Classical',           dates:'500 – 1500 CE',          instruments:['gayageum','gamelan','tabla'] },
  { id:'modern',   label:'Modern Traditional',  dates:'1500 CE – Present',      instruments:['janggu','dantranh','shakuhachi'] },
];
